EPSP preparation 1/X
AllenInstitute/MIES pull request #1605
Opened 2022-12-20 22:48 UTC by t-b

@michaelHuth Please review

2022-12-21 21:03 UTC, MichaelHuth requested changes
See comments.

2022-12-21 21:03 UTC, MichaelHuth commented on Packages/MIES/MIES_SweepFormula_Helpers.ipf
> +Function SFH_GetArgumentAsNumeric(variable jsonId, string jsonPath, string graph, string opShort, variable argNum, [variable defValue])
I think some brief function docu would be helpful.
(also for `SFH_GetArgumentAsWave`)

2022-12-22 11:55 UTC, MichaelHuth submitted a review, later dismissed
Looks good.

2022-12-22 13:26 UTC, t-b commented
@MichaelHuth Thanks for the review. Will merge once CI passes.

2022-12-23 18:40 UTC, merged