Small enhancements for SF
AllenInstitute/MIES pull request #1643
Opened 2023-03-06 15:39 UTC by t-b

@MichaelHuth Please have a look how I implemented the two new features.

2023-03-13 18:05 UTC, MichaelHuth requested changes
Looks good in general, just a few minor change requests.

2023-03-13 18:05 UTC, MichaelHuth commented on Packages/MIES/MIES_SweepFormula_Helpers.ipf
> +			Duplicate/FREE range, adaptedRange
Please add a note to the function description that the passed range should be treated as const.

2023-03-13 18:05 UTC, MichaelHuth commented on Packages/tests/Basic/UTF_JSONWaveNotes.ipf
> +	Note/K wv, "efgh\rJSON_BEGIN\r"
Maybe we should have the WAVE_NOTE_JSON_SEPARATOR non-static then to be usable in tests.

2023-03-14 14:50 UTC, t-b commented on Packages/MIES/MIES_SweepFormula.ipf
> +/// @brief Generate `numTraces` trace names for the given input
Done

2023-03-14 14:52 UTC, t-b commented on Packages/MIES/MIES_SweepFormula.ipf
> +							WAVE/SDFR=dfrWork customMarker = $wvName
Good point. Done.

2023-03-14 14:54 UTC, t-b commented on Packages/MIES/MIES_Constants.ipf
> +StrConstant SF_META_MOD_MARKER = "/Marker" // numeric wave
Done.

2023-03-14 14:54 UTC, t-b commented on Packages/MIES/MIES_Constants.ipf
> +StrConstant SF_META_SHOW_LEGEND = "/ShowLegend" // numeric, defaults to yes
Done.

2023-03-14 14:56 UTC, t-b commented on Packages/MIES/MIES_SweepFormula_Helpers.ipf
> +/// @brief Recreate the select data wave and range stored in the JSON wavenote from SFH_GetSweepsForFormula()
Done.

2023-03-14 15:11 UTC, t-b commented
@MichaelHuth I've responded to the feedback.

2023-03-14 19:23 UTC, merged