Avoid setting out of range DAScale values
AllenInstitute/MIES pull request #2184
Opened 2024-07-12 20:55 UTC by t-b

- [x] Add minimum/maximum to wavebuilder stimset note
- [ ] Fix #2180
- [ ] Add return value to SetDAScale/SetDAScaleModOp and let all analysis functions handle that.
- [ ] Fail with new LBN entry in this case and suggest to change "External Command Sensitiviy", add test, dashboard check, adapt flowchart, raise version
	- [ ] SC_SpikeControl
	- [ ] PSQ_Chirp
	- [ ] ReachTargetVoltage
	- [ ] MSQ_FastRheoEst
	- [ ] MSQ_DAScale
	- [ ] PSQ_DAScale
	- [ ] PSQ_SquarePulse
	- [ ] PSQ_Rheobase
	- [ ] PSQ_Ramp

Open questions:
- We always want to set the DAScale value for the **next** sweep. And for that we would need the stimsetColumn for the next sweep, which we don't have. DC_CalculateChannelColumnNo can calculate the new stimsetColumn, but not without changing the internal state. Is there a way we can fix this here without implementing #39? Maybe we can assume that the min/max of all sweeps of a stimset are constant? 

Close #2120

2024-12-03 20:24 UTC, t-b commented
@timjarsky Can be reviewed once #2290 is merged.

2025-01-09 20:19 UTC, timjarsky commented
@t-b 
```
  Some values in DataWave exceed device limits for DATA_ACQUISITION mode (channel index 1, position 3467). Maybe the DA/AD Gain needs adjustment?
```

With small amplitude events. See PXP.

[2025_01_09_112350.zip](https://github.com/user-attachments/files/18366902/2025_01_09_112350.zip)

2025-01-14 18:47 UTC, t-b commented
> ```
>   Some values in DataWave exceed device limits for DATA_ACQUISITION mode (channel index 1, position 3467). Maybe the DA/AD Gain needs adjustment?
> ```
> 
> With small amplitude events. See PXP.
> 
> [2025_01_09_112350.zip](https://github.com/user-attachments/files/18366902/2025_01_09_112350.zip)



> @t-b
> 
> ```
>   Some values in DataWave exceed device limits for DATA_ACQUISITION mode (channel index 1, position 3467). Maybe the DA/AD Gain needs adjustment?
> ```
> 
> With small amplitude events. See PXP.

I see the exact same behaviour in main and also in the older 2.7 version. The scale value of 330 for DA1 seems to be too high.

2025-01-15 18:57 UTC, timjarsky commented
> > ```
> >   Some values in DataWave exceed device limits for DATA_ACQUISITION mode (channel index 1, position 3467). Maybe the DA/AD Gain needs adjustment?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With small amplitude events. See PXP.
> 
> I see the exact same behaviour in main and also in the older 2.7 version. The scale value of 330 for DA1 seems to be too high.

@t-b I think I was in VC when I thought I was in CC. I'll double-check.

2025-01-15 19:48 UTC, timjarsky requested changes
```  Some values in DataWave exceed device limits for DATA_ACQUISITION mode (channel index 1, position 53333). Maybe the DA/AD Gain needs adjustment?'''

Instead of suggesting the gain adjustment, suggest a DA scale adjustment.

2025-01-20 14:43 UTC, t-b commented
Will merge once CI passes per https://github.com/AllenInstitute/MIES/pull/2184#pullrequestreview-2553752731.

2025-01-21 12:49 UTC, merged