Fix for PA_CalculatePulseStartTimes sometimes ignoring the first pulse
AllenInstitute/MIES pull request #697
Opened 2020-10-26 18:46 UTC by MichaelHuth

The issue was that for the case that totalOnSetDelay equals the start time of
the first pulse then FindLevels could not detect the first edge any more.

The fix is that FindLevels starts now from totalOnsetDelay - delta.
Start position is capped to be >= 0.

close https://github.com/AllenInstitute/MIES/issues/691

2020-10-26 20:25 UTC, t-b requested changes

2020-10-26 20:25 UTC, t-b commented on Packages/MIES/MIES_PulseAveraging.ipf
> +	MultiThread junkWave = ZeroWave(set[p]) + PA_UpdateMinAndMax(set[p])
@MichaelHuth unrelated change?

2020-10-26 20:28 UTC, MichaelHuth commented on Packages/MIES/MIES_PulseAveraging.ipf
> +	MultiThread junkWave = ZeroWave(set[p]) + PA_UpdateMinAndMax(set[p])
Yes, thats weird. I kick that out.

2020-10-27 10:54 UTC, t-b approved these changes
LGTM

2020-10-29 17:55 UTC, timjarsky commented
@MichaelHuth If we ever need to look back at this PR it may be helpful to define delta in the description.

2020-10-29 17:55 UTC, timjarsky approved these changes

2020-10-29 19:04 UTC, t-b commented
@timjarsky The code has `delta = DimDelta(DA, ROWS)` so I think we should be able to get an understanding of the logic.

2020-10-29 19:04 UTC, merged